### ISSUE TITLE
Version bump

### ISSUE THREAD

**Issue by simonhildebrandt** [RobertMenke/rm-emoji-picker#22]
I'm having trouble pulling our new version from NPM, and I think it's 'cause I forgot to include a version bump in my PR - sorry. :/

Could we get a version bump and a new package published?

**Comment by RobertMenke** [comment]
Hmm I thought I pushed it out. I just pushed out a new version to make sure. Can you try that? The version should be 3.1.10

**Comment by simonhildebrandt** [comment]
That did it! I notice that the package still comes with `non_npm_dependencies/iamcal_js_emoji` which I don't think it needs anymore, since I added into devDependencies - but my emojis look right now because it's pulling from the right `emoji-js` data file, I think. :)

**Comment by RobertMenke** [comment]
Good! I'm going to leave it in for now since I can't recall off the top of my head if I'm referencing those somewhere. Sometime in the next few weeks, I want to make a somewhat larger update and add in the ability to choose which style of emojis you want to work with so I'll do some clean up then. Thanks for catching that @simonhildebrandt!
