### ISSUE TITLE
Bug: event is undefined.

### ISSUE THREAD

**Issue by dondoco7** [RobertMenke/rm-emoji-picker#27]
event is undefined error by firefox .

```
  openPicker() {
        ...
        this._onTooltipClick(tooltip, event);  <- this is undefined.
        ...
  }
```

and I want to change rm-tooltip#setClickCallback;
```
Tooltip.prototype.setClickCallback = function(event, func){

    if (event) {
      event.stopPropagation();
    }

    this._unique = 'click.' + new Date().getTime();

    $("html").on(this._unique, event => {
        func.call(this, event.target, this.$tooltip);
    });
};

```

**Comment by RobertMenke** [comment]
@dondoco7 This was an AWESOME catch. Thank you for reporting this! Instead of changing the tooltip library I just fixed the reference error in the emoji picker by passing the MouseEvent to `openPicker()` in this PR https://github.com/RobertMenke/rm-emoji-picker/pull/28.

Please re-open if this doesn't fix your issue!
